name: Build EXE
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: Build single exe
        run: |
          pyinstaller -wF "1时段定时播放器.py"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 定时播放器成品EXE
          path: dist/*.exe
